# Standards: 1.1.5
---

# 1.2.2 Ensure GPG keys are configured

# The remediation actions for this recommendation are site-specific, therefore we test that
# executing the specified rpm command results in no errors.
- name: 1.2.2 - Ensure GPG keys are configured
  shell: rpm -q gpg-pubkey --qf '%{name}-%{version}-%{release} --> %{summary}\n'
#  register: gpg-pubkey_check
  args:
    warn: false
  tags:
    - level-1
    - "1.2.2"
    - scored
    - skip_ansible_lint

#- name: 1.2.2 - Check GPG keys are configured
#  debug:
#    msg: GPG keys are incorrectly configured
#  when:
